import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import "./animation.css";
import { EdgeStoreProvider } from "@/lib/edgestore";
import ProgressBarProvider from "@/utils/progressbar-provider";
import { cn } from "@/lib/utils";

const font = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Barangay Banaba East Batangas City",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          font.variable
        )}
      >
        <EdgeStoreProvider>
          <ProgressBarProvider>
            <Toaster richColors />
            {children}
          </ProgressBarProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
