import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import "./animation.css";
import { EdgeStoreProvider } from "@/lib/edgestore";
import ProgressBarProvider from "@/utils/progressbar-provider";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "@/utils/react-query-provider";
import { ActiveUserProvider } from "@/utils/active-user-provider";

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Barangay Banaba East Batangas City",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          font.className
        )}
      >
        <EdgeStoreProvider>
          <ProgressBarProvider>
            <ActiveUserProvider>
              <Toaster richColors />
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </ActiveUserProvider>
          </ProgressBarProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
